### ISSUE TITLE
How to convert iterable of tuples to dict?

### ISSUE THREAD

**Issue by laundmo** [dwt/fluent#12]
Hey there, i have a fluentpy expression along these lines
```py
a = [1,2,3,4]
b = "abcd"
_(a).zip(b).print()._
```
This gives me a iterable of 2-tuples. Obviously, i could wrap this in a dict() call, but that is not really fluent.
```py
dict(_(a).zip(b)._)
```
Is there a fluent way to do this conversion?

**Comment by dwt** [comment]
Not quite sure what you want to achieve, but the easiest way to pull free functions into the fluentpy call chain is the `.call()` helper. Use it like this:

```shell
python -m fluentpy '_([1,2,3,4]).zip("abcd").call(dict).print()‘
{1: 'a', 2: 'b', 3: 'c', 4: 'd'}
```

If that helps, feel free to close the issue. :-)

Best Regards
Martin Häcker

**Comment by laundmo** [comment]
That is exactly what i was looking for, thanks!
