### ISSUE TITLE
How to type conversion?

### ISSUE THREAD

**Issue by GF-Huang** [dwt/fluent#9]
```py
>>> _('123.456').int()
123.456
```

**Comment by dwt** [comment]
Interesting question - I've never thought about adding number conversion methods directly yet. Now that I think about it, that looks like a glaring omission indeed. :-)


For now, you can do the conversion the same way than calling any other free method:

```python
>>> _('123.456').call(float).call(int)
fluentpy.wrap(123)
```

The conversion to float first is neccessary in this example as `int()` doesn't accept float literals as input and raises in that case.

I'll see that I add some of these conversions as instance methods in one of the next releases - thanks for the input!

**Comment by GF-Huang** [comment]
Got it, thanks.
